require_relative 'parsers/parser'
require_relative 'parsers/trivial_parser'
require_relative 'parsers/yaml_parser'
require_relative 'parsers/string_parser'
require_relative 'parsers/string_fantom_parser'
require_relative 'parsers/splittable_parser'
require_relative 'parsers/jaspar_parser'